ERRNO_DEF(EPERM, 1, "Operation not")
ERRNO_DEF(ENOENT, 2, "No such file or")
ERRNO_DEF(ESRCH, 3, "No such")
ERRNO_DEF(EINTR, 4, "Interrupted system")
ERRNO_DEF(EIO, 5, "Input/output")
ERRNO_DEF(ENXIO, 6, "Device not")
ERRNO_DEF(E2BIG, 7, "Argument list too")
ERRNO_DEF(ENOEXEC, 8, "Exec format")
ERRNO_DEF(EBADF, 9, "Bad file")
ERRNO_DEF(ECHILD, 10, "No child")
ERRNO_DEF(EDEADLK, 11, "Resource deadlock")
ERRNO_DEF(ENOMEM, 12, "Cannot allocate")
ERRNO_DEF(EACCES, 13, "Permission")
ERRNO_DEF(EFAULT, 14, "Bad")
ERRNO_DEF(ENOTBLK, 15, "Block device")
ERRNO_DEF(EBUSY, 16, "Device")
ERRNO_DEF(EEXIST, 17, "File")
ERRNO_DEF(EXDEV, 18, "Cross-device")
ERRNO_DEF(ENODEV, 19, "Operation not supported by")
ERRNO_DEF(ENOTDIR, 20, "Not a")
ERRNO_DEF(EISDIR, 21, "Is a")
ERRNO_DEF(EINVAL, 22, "Invalid")
ERRNO_DEF(ENFILE, 23, "Too many open files in")
ERRNO_DEF(EMFILE, 24, "Too many open")
ERRNO_DEF(ENOTTY, 25, "Inappropriate ioctl for")
ERRNO_DEF(ETXTBSY, 26, "Text file")
ERRNO_DEF(EFBIG, 27, "File too")
ERRNO_DEF(ENOSPC, 28, "No space left on")
ERRNO_DEF(ESPIPE, 29, "Illegal")
ERRNO_DEF(EROFS, 30, "Read-only")
ERRNO_DEF(EMLINK, 31, "Too many")
ERRNO_DEF(EPIPE, 32, "Broken")
ERRNO_DEF(EDOM, 33, "Numerical argument out of")
ERRNO_DEF(ERANGE, 34, "Result too")
ERRNO_DEF(EAGAIN, 35, "Resource temporarily")
ERRNO_DEF(EINPROGRESS, 36, "Operation now in")
ERRNO_DEF(EALREADY, 37, "Operation already in")
ERRNO_DEF(ENOTSOCK, 38, "Socket operation on")
ERRNO_DEF(EDESTADDRREQ, 39, "Destination address")
ERRNO_DEF(EMSGSIZE, 40, "Message too")
ERRNO_DEF(EPROTOTYPE, 41, "Protocol wrong type for")
ERRNO_DEF(ENOPROTOOPT, 42, "Protocol not")
ERRNO_DEF(EPROTONOSUPPORT, 43, "Protocol not")
ERRNO_DEF(ESOCKTNOSUPPORT, 44, "Socket type not")
ERRNO_DEF(ENOTSUP, 45, "Operation not")
ERRNO_DEF(EPFNOSUPPORT, 46, "Protocol family not")
ERRNO_DEF(EAFNOSUPPORT, 47, "Address family not supported by protocol")
ERRNO_DEF(EADDRINUSE, 48, "Address already in")
ERRNO_DEF(EADDRNOTAVAIL, 49, "Can't assign requested")
ERRNO_DEF(ENETDOWN, 50, "Network is")
ERRNO_DEF(ENETUNREACH, 51, "Network is")
ERRNO_DEF(ENETRESET, 52, "Network dropped connection on")
ERRNO_DEF(ECONNABORTED, 53, "Software caused connection")
ERRNO_DEF(ECONNRESET, 54, "Connection reset by")
ERRNO_DEF(ENOBUFS, 55, "No buffer space")
ERRNO_DEF(EISCONN, 56, "Socket is already")
ERRNO_DEF(ENOTCONN, 57, "Socket is not")
ERRNO_DEF(ESHUTDOWN, 58, "Can't send after socket")
ERRNO_DEF(ETOOMANYREFS, 59, "Too many references: can't")
ERRNO_DEF(ETIMEDOUT, 60, "Operation timed")
ERRNO_DEF(ECONNREFUSED, 61, "Connection")
ERRNO_DEF(ELOOP, 62, "Too many levels of symbolic")
ERRNO_DEF(ENAMETOOLONG, 63, "File name too")
ERRNO_DEF(EHOSTDOWN, 64, "Host is")
ERRNO_DEF(EHOSTUNREACH, 65, "No route to")
ERRNO_DEF(ENOTEMPTY, 66, "Directory not")
ERRNO_DEF(EPROCLIM, 67, "Too many")
ERRNO_DEF(EUSERS, 68, "Too many")
ERRNO_DEF(EDQUOT, 69, "Disc quota")
ERRNO_DEF(ESTALE, 70, "Stale NFS file")
ERRNO_DEF(EREMOTE, 71, "Too many levels of remote in")
ERRNO_DEF(EBADRPC, 72, "RPC struct is")
ERRNO_DEF(ERPCMISMATCH, 73, "RPC version")
ERRNO_DEF(EPROGUNAVAIL, 74, "RPC prog. not")
ERRNO_DEF(EPROGMISMATCH, 75, "Program version")
ERRNO_DEF(EPROCUNAVAIL, 76, "Bad procedure for")
ERRNO_DEF(ENOLCK, 77, "No locks")
ERRNO_DEF(ENOSYS, 78, "Function not")
ERRNO_DEF(EFTYPE, 79, "Inappropriate file type or")
ERRNO_DEF(EAUTH, 80, "Authentication")
ERRNO_DEF(ENEEDAUTH, 81, "Need")
ERRNO_DEF(EIDRM, 82, "Identifier")
ERRNO_DEF(ENOMSG, 83, "No message of desired")
ERRNO_DEF(EOVERFLOW, 84, "Value too large to be stored in data")
ERRNO_DEF(ECANCELED, 85, "Operation")
ERRNO_DEF(EILSEQ, 86, "Illegal byte")
ERRNO_DEF(ENOATTR, 87, "Attribute not")
ERRNO_DEF(EDOOFUS, 88, "Programming")
ERRNO_DEF(EBADMSG, 89, "Bad")
ERRNO_DEF(EMULTIHOP, 90, "Multihop")
ERRNO_DEF(ENOLINK, 91, "Link has been")
ERRNO_DEF(EPROTO, 92, "Protocol")
ERRNO_DEF(ENOTCAPABLE, 93, "Capabilities")
ERRNO_DEF(ECAPMODE, 94, "Not permitted in capability")
ERRNO_DEF(ENOTRECOVERABLE, 95, "State not")
ERRNO_DEF(EOWNERDEAD, 96, "Previous owner")
